### ISSUE TITLE
[Admin Action] Removing "resume" spam

### ISSUE THREAD

**Issue by colmdoyle** [IrishTechCommunity/irishtechcommunity.github.io#25]
https://irishtechcommunity.slack.com/files/yawargenii/F0SEX9L02/resume.pdf
https://irishtechcommunity.slack.com/files/yawargenii/F0SEBEVLL/resume.pdf
https://irishtechcommunity.slack.com/files/yawargenii/F0SEY4466/resume.pdf

**Comment by Shane24** [comment]
:+1:

**Comment by colmdoyle** [comment]
done

**Comment by oisin** [comment]
:+1:
